### ISSUE TITLE
กรุณา"อย่า"ละเมิดสิทธิ์และสิทธิส่วนบุคคล

### ISSUE THREAD

**Issue by Atkinson2646** [akirataguchi115/akirataguchi115#4]
กรุณา"อย่า"ละเมิดสิทธิ์และสิทธิส่วนบุคคล

_Originally posted by @nongmai22 in https://github.com/akirataguchi115/akirataguchi115/issues/1#issuecomment-1543750237_

**Comment by nongmai22** [comment]
มึงเจ้าของเหรออีสัตว์
